# .github/FUNDING.yml
github: [adrianaliveappstudio]   # Your GitHub username
patreon: adrianasamusic          # Example Patreon handle
open_collective: adrianalive     # Example Open Collective
ko_fi: adrianasamusic            # Example Ko-fi
custom: ["https://paypal.me/adrianasamusic", "https://buymeacoffee.com/adrianasamusic"]
